const fs = require("fs").promises;
const solc = require("solc");

async function main() {
  // Load the contract source code
  const sourceCode = await fs.readFile("DoubleAuction.sol", "utf8");

  // Compile the source code and retrieve the ABI and bytecode
  const { abi, bytecode } = compile(sourceCode, "DoubleAuction");

  // Store the ABI and bytecode into a JSON file
  const artifact = JSON.stringify({ abi, bytecode }, null, 2);
  await fs.writeFile("DoubleAuction.json", artifact);
}

function compile(sourceCode, contractName) {
  /*
    Important:
    This Quorum/Geth VM is older, so we force an older EVM target.

    Without this, newer solc versions may generate newer opcodes like PUSH0,
    and deployment can fail by consuming the entire gas limit.
  */
  const input = {
    language: "Solidity",
    sources: {
      main: {
        content: sourceCode,
      },
    },
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },

      // This keeps the generated bytecode compatible with the older Quorum VM.
      evmVersion: "istanbul",

      outputSelection: {
        "*": {
          "*": ["abi", "evm.bytecode"],
        },
      },
    },
  };

  const output = JSON.parse(solc.compile(JSON.stringify(input)));

  // Print compiler errors/warnings if any, but do not crash on warnings only.
  if (output.errors) {
    for (const error of output.errors) {
      console.error(error.formattedMessage);
    }
  }

  const artifact = output.contracts.main[contractName];

  return {
    abi: artifact.abi,
    bytecode: artifact.evm.bytecode.object,
  };
}

main().then(() => process.exit(0));
